eng_list = ['I am the life of the party.',
 "I don't talk a lot.",
 'I feel comfortable around people.',
 'I keep in the background.',
 'I start conversations.',
 'I have little to say.',
 'I talk to a lot of different people at parties.',
 "I don't like to draw attention to myself.",
 "I don't mind being the center of attention.",
 'I am quiet around strangers.',
 'I get stressed out easily.',
 'I am relaxed most of the time.',
 'I worry about things.',
 'I seldom feel blue.',
 'I am easily disturbed.',
 'I get upset easily.',
 'I change my mood a lot.',
 'I have frequent mood swings.',
 'I get irritated easily.',
 'I often feel blue.',
 'I feel little concern for others.',
 'I am interested in people.',
 'I insult people.',
 "I sympathize with others' feelings.",
 "I am not interested in other people's problems.",
 'I have a soft heart.',
 'I am not really interested in others.',
 'I take time out for others.',
 "I feel others' emotions.",
 'I make people feel at ease.',
 'I am always prepared.',
 'I leave my belongings around.',
 'I pay attention to details.',
 'I make a mess of things.',
 'I get chores done right away.',
 'I often forget to put things back in their proper place.',
 'I like order.',
 'I shirk my duties.',
 'I follow a schedule.',
 'I am exacting in my work.',
 'I have a rich vocabulary.',
 'I have difficulty understanding abstract ideas.',
 'I have a vivid imagination.',
 'I am not interested in abstract ideas.',
 'I have excellent ideas.',
 'I do not have a good imagination.',
 'I am quick to understand things.',
 'I use difficult words.',
 'I spend time reflecting on things.',
 'I am full of ideas.']

port_list = ['Sou uma das pessoas que mais anima as festas.',
"Não falo muito.",
'Eu me sinto confortável perto das pessoas.',
'Eu mantenho em segundo plano.',
'Eu começo conversas.',
'Eu tenho pouco a dizer.',
'Eu converso com muitas pessoas diferentes em festas.',
"Não gosto de chamar atenção para mim.",
"Não me importo de ser o centro das atenções.",
'Eu fico quieto perto de estranhos.',
'Eu fico estressado facilmente.',
'Estou relaxado na maior parte do tempo.',
'Eu me preocupo com as coisas.',
'Raramente me sinto triste.',
'Eu sou facilmente perturbado.',
'Eu fico chateado facilmente.',
'Eu mudo muito meu humor.',
'Eu tenho mudanças de humor frequentes.',
'Eu fico irritado facilmente.',
'Muitas vezes me sinto triste.',
'Eu não me preocupo com os outros.',
'Eu sou interessado nas pessoas.',
'Eu insulto as pessoas.',
"Simpatizo com os sentimentos dos outros.",
"Não estou interessado nos problemas de outras pessoas.",
'Eu tenho um coração mole.',
'Não sou realmente interessado nos outros.',
'Eu tiro tempo para os outros.',
"Eu sinto as emoções dos outros.",
'Eu faço as pessoas se sentirem à vontade.',
'Estou sempre preparado.',
'Eu deixo meus pertences por aí.',
'Eu presto atenção aos detalhes.',
'Eu bagunço as coisas.',
'Eu faço as tarefas imediatamente.',
'Muitas vezes me esqueço de colocar as coisas de volta em seus devidos lugares.',
'Eu gosto de ordem.',
'Eu evito meus deveres.',
'Eu sigo um cronograma.',
'Eu sou exigente no meu trabalho.',
'Eu tenho um vocabulário rico.',
'Tenho dificuldade em compreender ideias abstratas.',
'Eu tenho uma imaginação fértil.',
'Não estou interessado em ideias abstratas.',
'Tenho excelentes ideias.',
'Eu não tenho uma boa imaginação.',
'Eu sou rápido para entender as coisas.',
'Eu uso palavras difíceis.',
'Eu passo tempo refletindo sobre as coisas.',
'Sou cheio de ideias.']